import type { Metadata } from "next";
import Providers from "@app/lib/providers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Delivery Platform",
  description: "Generated by Devco Solutions",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Add your custom root layout code here
  return <Providers>{children}</Providers>;
}
